/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p3;

import p3.Proxy.Proxy;

public class App {
    public static final int PORT = 12345;

    public static void main(String[] args) {
        Proxy proxy = new Proxy(PORT);
        proxy.run();
    }
}
